### ISSUE TITLE
Allowing multiple instances

### ISSUE THREAD

**Issue by chibicitiberiu** [ihtfw/Logazmic#4]
I need to compare some log files, and there's no way you can do that with Logazmic. There is no option to view files side by side, and I cannot open multiple windows as it forces me to use tabs.

Can there be an option to disable this "single instance" policy, and let me view multiple files at the same time? 

Thank you.

**Comment by ihtfw** [comment]
This limitation was added to avoid conflicts in settings files, because every instance would rewrite them.

Comparing files is interesting scenario, so I've add new option "single window"(default is true). So make it false and open as many windows as you want, but it could cause some troubles with settings.

Version 2020.5.15.35

Maybe there would be error while updating, if yes then please download latest Setup.exe from releases page
